# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16ea2e60345d8ed3c746181b368a7e25d1f03d370d3efa3e1c1e715a966f270e89c897fc3f8be56ca357815e57fd6f9f8ec2130657d3c70ba40e915c15d824f7

test:
  secret_key_base: 5af120c69a38a94b99eecb6338ab8bf14a57fe839067c3151f0bd71394daf5f15b798ac6e39dab7e0062c74d10071eb305e927afb8b4d312fd5c9c4329595fb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
